using System;


namespace clod_rest_server
{
    public class PlaneInformation
    {
        public Double? Nil { get; set; }
        public Double? M_Random { get; set; }
        public Double? M_Shake { get; set; }
        public Double? M_CabinDamage { get; set; }
        public Double? M_CabinState { get; set; }
        public Double? M_NamedDamage { get; set; }
        public Double? M_SystemWear { get; set; }
        public Double? M_Health { get; set; }
        public Double? C_Steering { get; set; }
        public Double? C_Brake { get; set; }
        public Double? C_Throttle { get; set; }
        public Double? C_Trigger { get; set; }
        public Double? C_Pitch { get; set; }
        public Double? C_Mix { get; set; }
        public Double? C_WaterRadiator { get; set; }
        public Double? C_OilRadiator { get; set; }
        public Double? C_RadiatorAutomation { get; set; }
        public Double? C_PitchAutomation { get; set; }
        public Double? C_Compressor { get; set; }
        public Double? C_Afterburner { get; set; }
        public Double? C_BoostEnabler { get; set; }
        public Double? C_SlowRunningCutOut { get; set; }
        public Double? C_Magneto { get; set; }
        public Double? C_Feather { get; set; }
        public Double? C_CarbHeater { get; set; }
        public Double? C_HatchDoor { get; set; }
        public Double? C_HatchJettison { get; set; }
        public Double? C_Timer { get; set; }
        public Double? C_Timer1 { get; set; }
        public Double? C_Aileron { get; set; }
        public Double? C_Elevator { get; set; }
        public Double? C_Rudder { get; set; }
        public Double? C_AileronTrim { get; set; }
        public Double? C_ElevatorTrim { get; set; }
        public Double? C_RudderTrim { get; set; }
        public Double? C_TailwheelLock { get; set; }
        public Double? C_LandingFlap { get; set; }
        public Double? C_LeadingEdgeSlats { get; set; }
        public Double? C_Undercarriage { get; set; }
        public Double? C_UndercarriageEmergency { get; set; }
        public Double? C_BombBayDoor { get; set; }
        public Double? C_Airbrake { get; set; }
        public Double? C_FuelTankSelector { get; set; }
        public Double? C_TelepirometroElettrico { get; set; }
        public Double? C_AltimeterPinion { get; set; }
        public Double? C_AnemometroPinion { get; set; }
        public Double? C_BombSight { get; set; }
        public Double? C_Sight { get; set; }
        public Double? C_Bombenabwurfgerat { get; set; }
        public Double? C_KraftstoffSelector { get; set; }
        public Double? C_LiquidGauge0 { get; set; }
        public Double? C_LiquidGauge1 { get; set; }
        public Double? C_PriLights { get; set; }
        public Double? C_SecLights { get; set; }
        public Double? C_SightLights { get; set; }
        public Double? C_PitotHeater { get; set; }
        public Double? C_Handpumpe { get; set; }
        public Double? C_RadTXRX { get; set; }
        public Double? C_RadPriNav { get; set; }
        public Double? C_RadSecNav { get; set; }
        public Double? C_Kurssteuerung { get; set; }
        public Double? A_Steering { get; set; }
        public Double? A_Brake { get; set; }
        public Double? A_Aileron { get; set; }
        public Double? A_Elevator { get; set; }
        public Double? A_Rudder { get; set; }
        public Double? A_AileronTrim { get; set; }
        public Double? A_ElevatorTrim { get; set; }
        public Double? A_RudderTrim { get; set; }
        public Double? A_Undercarriage { get; set; }
        public Double? A_UndercarriageShock { get; set; }
        public Double? A_UndercarriageWheel { get; set; }
        public Double? A_HatchDoor { get; set; }
        public Double? A_BombBayDoor { get; set; }
        public Double? A_ImpellerAngle { get; set; }
        public Double? A_ImpellerAngularVelocity { get; set; }
        public Double? A_ImpellerUnfold { get; set; }
        public Double? A_LandingFlap { get; set; }
        public Double? A_Airbrake { get; set; }
        public Double? A_EngineAirRadiator { get; set; }
        public Double? A_EngineWaterRadiator { get; set; }
        public Double? A_EngineOilRadiator { get; set; }
        public Double? A_LeadingEdgeSlat { get; set; }
        public Double? Z_Coordinates { get; set; }
        public Double? Z_Orientation { get; set; }
        public Double? Z_Overload { get; set; }
        public Double? Z_AltitudeAGL { get; set; }
        public Double? Z_AltitudeMSL { get; set; }
        public Double? Z_VelocityIAS { get; set; }
        public Double? Z_VelocityTAS { get; set; }
        public Double? Z_VelocityMach { get; set; }
        public Double? Z_AmbientAirTemperature { get; set; }
        public Double? S_ElectricVoltage { get; set; }
        public Double? S_ElectricIncandescingRatio { get; set; }
        public Double? S_ElectricAmperage { get; set; }
        public Double? S_ElectricPrimaryPitLight { get; set; }
        public Double? S_ElectricSecondaryPitLight { get; set; }
        public Double? S_ElectricSightLight { get; set; }
        public Double? S_FuelReserve { get; set; }
        public Double? S_HatchDoor { get; set; }
        public Double? S_UndercarriageValve { get; set; }
        public Double? S_PneumoContainerPressure { get; set; }
        public Double? S_PneumoLinePressure { get; set; }
        public Double? S_HydroPressure { get; set; }
        public Double? S_HydroReserve { get; set; }
        public Double? S_Sturzanlage { get; set; }
        public Double? S_GunOperation { get; set; }
        public Double? S_GunReserve { get; set; }
        public Double? S_GunClipReserve { get; set; }
        public Double? S_BombReserve { get; set; }
        public Double? S_Fenster { get; set; }
        public Double? S_PitotHeater { get; set; }
        public Double? S_Bombenabwurfgerat { get; set; }
        public Double? S_Turret { get; set; }
        public Double? M_Reserved000 { get; set; }
        public Double? M_Reserved001 { get; set; }
        public Double? M_Reserved002 { get; set; }
        public Double? M_Reserved003 { get; set; }
        public Double? M_Reserved004 { get; set; }
        public Double? M_Reserved005 { get; set; }
        public Double? M_Reserved006 { get; set; }
        public Double? M_Reserved007 { get; set; }
        public Double? M_Reserved008 { get; set; }
        public Double? M_Reserved009 { get; set; }
        public Double? M_Reserved00A { get; set; }
        public Double? M_Reserved00B { get; set; }
        public Double? M_Reserved00C { get; set; }
        public Double? M_Reserved00D { get; set; }
        public Double? M_Reserved00E { get; set; }
        public Double? M_Reserved00F { get; set; }
        public Double? M_Reserved010 { get; set; }
        public Double? M_Reserved011 { get; set; }
        public Double? M_Reserved012 { get; set; }
        public Double? M_Reserved013 { get; set; }
        public Double? M_Reserved014 { get; set; }
        public Double? M_Reserved015 { get; set; }
        public Double? M_Reserved016 { get; set; }
        public Double? M_Reserved017 { get; set; }
        public Double? M_Reserved018 { get; set; }
        public Double? M_Reserved019 { get; set; }
        public Double? M_Reserved01A { get; set; }
        public Double? M_Reserved01B { get; set; }
        public Double? M_Reserved01C { get; set; }
        public Double? M_Reserved01D { get; set; }
        public Double? M_Reserved01E { get; set; }
        public Double? M_Reserved01F { get; set; }
        public Double? I_Timer { get; set; }
        public Double? I_AmbientTemp { get; set; }
        public Double? I_EngineRPM { get; set; }
        public Double? I_EngineManPress { get; set; }
        public Double? I_EngineBoostPress { get; set; }
        public Double? I_EngineWatPress { get; set; }
        public Double? I_EngineOilPress { get; set; }
        public Double? I_EngineFuelPress { get; set; }
        public Double? I_EngineWatTemp { get; set; }
        public Double? I_EngineRadTemp { get; set; }
        public Double? I_EngineOilTemp { get; set; }
        public Double? I_EngineOilRadiatorTemp { get; set; }
        public Double? I_EngineTemperature { get; set; }
        public Double? I_EngineCarbTemp { get; set; }
        public Double? I_Pitch { get; set; }
        public Double? I_VelocityIAS { get; set; }
        public Double? I_Altitude { get; set; }
        public Double? I_Variometer { get; set; }
        public Double? I_Slip { get; set; }
        public Double? I_MagneticCompass { get; set; }
        public Double? I_RepeaterCompass { get; set; }
        public Double? I_Peilzeiger { get; set; }
        public Double? I_FuelReserve { get; set; }
        public Double? I_LiquidReserve { get; set; }
        public Double? I_Voltamperemeter { get; set; }
        public Double? I_Voltmeter { get; set; }
        public Double? I_Amperemeter { get; set; }
        public Double? I_HydroPressure { get; set; }
        public Double? I_HydroEmPressure { get; set; }
        public Double? I_Turn { get; set; }
        public Double? I_AH { get; set; }
        public Double? I_DirectionIndicator { get; set; }
        public Double? I_SlavedCompass { get; set; }
        public Double? I_Suction { get; set; }
        public Double? I_AFN { get; set; }
        public Double? I_ADF { get; set; }
        public Double? I_RDF { get; set; }
        public Double? I_RMI { get; set; }
        public Double? I_FLRC { get; set; }
        public Double? I_Kurssteuerung { get; set; }
        public Double? I_BombSight { get; set; }
    }

}
